import type {
  ChatMessage,
  KnowledgeLink,
  Note,
  Project,
  Source,
  Topic,
} from "./types";

export const demoTopics: Topic[] = [
  {
    id: "topic-ai-creativity",
    title: "الذكاء الاصطناعي والإبداع",
    description: "كيف تعزز الأدوات الذكية التفكير الإنساني من دون أن تستبدله.",
    color: "#7968e8",
    icon: "✦",
    stage: "معرفة",
    noteCount: 12,
    sourceCount: 7,
    progress: 76,
    updatedAt: "2026-07-28T08:30:00.000Z",
  },
  {
    id: "topic-learning",
    title: "علوم التعلّم",
    description: "الذاكرة، الاسترجاع، وبناء أنظمة تعلم تبقى لسنوات.",
    color: "#e79f66",
    icon: "◉",
    stage: "بحث",
    noteCount: 9,
    sourceCount: 11,
    progress: 58,
    updatedAt: "2026-07-27T18:10:00.000Z",
  },
  {
    id: "topic-music",
    title: "الموسيقى وعلم النفس",
    description: "أثر الإيقاع والتوقع الموسيقي في المشاعر والسلوك.",
    color: "#55a69b",
    icon: "♫",
    stage: "موثّق",
    noteCount: 8,
    sourceCount: 5,
    progress: 64,
    updatedAt: "2026-07-25T11:00:00.000Z",
  },
  {
    id: "topic-product",
    title: "تصميم المنتجات",
    description: "تحويل المشكلات المعقدة إلى تجارب بسيطة وقابلة للاختبار.",
    color: "#d36c72",
    icon: "◇",
    stage: "تطبيق",
    noteCount: 6,
    sourceCount: 4,
    progress: 83,
    updatedAt: "2026-07-24T14:20:00.000Z",
  },
];

export const demoNotes: Note[] = [
  {
    id: "note-1",
    title: "الإبداع عملية وصل لا لحظة إلهام",
    content:
      "الفكرة الجديدة غالباً تركيب غير متوقع بين نمطين معروفين. قيمة النظام المعرفي تأتي من تحسين احتمال اللقاء بين المعلومتين المناسبتين.",
    summary:
      "الإبداع ينمو حين يسهل النظام اكتشاف الروابط البعيدة بين المعارف.",
    kind: "idea",
    stage: "معرفة",
    tags: ["إبداع", "روابط", "تفكير"],
    topicId: "topic-ai-creativity",
    topicTitle: "الذكاء الاصطناعي والإبداع",
    createdAt: "2026-07-26T09:15:00.000Z",
    updatedAt: "2026-07-28T07:15:00.000Z",
  },
  {
    id: "note-2",
    title: "لماذا ينجح الاسترجاع النشط؟",
    content:
      "محاولة تذكر المعلومة تقوي مسارات الوصول إليها أكثر من إعادة قراءتها. الاختبار ليس أداة قياس فقط، بل أداة تعلم.",
    summary: "الاسترجاع النشط يبني الذاكرة عبر جهد التذكر نفسه.",
    kind: "research",
    stage: "موثّق",
    tags: ["ذاكرة", "تعلم", "استرجاع"],
    topicId: "topic-learning",
    topicTitle: "علوم التعلّم",
    createdAt: "2026-07-25T13:00:00.000Z",
    updatedAt: "2026-07-27T12:40:00.000Z",
  },
  {
    id: "note-3",
    title: "التوقع الموسيقي وتكوين المشاعر",
    content:
      "يبني المستمع توقعاً مستمراً لما سيأتي. التوتر بين التوقع والمفاجأة يصنع جزءاً مهماً من الاستجابة العاطفية.",
    summary: "المشاعر الموسيقية تتشكل من لعبة التوقع والمفاجأة.",
    kind: "note",
    stage: "بحث",
    tags: ["موسيقى", "مشاعر", "توقع"],
    topicId: "topic-music",
    topicTitle: "الموسيقى وعلم النفس",
    createdAt: "2026-07-23T16:30:00.000Z",
    updatedAt: "2026-07-26T10:10:00.000Z",
  },
  {
    id: "note-4",
    title: "سؤال: متى تتحول المعرفة إلى مشروع؟",
    content:
      "نحتاج معياراً يلتقط تكرار الأفكار، وضوح المشكلة، ووجود نتيجة قابلة للقياس قبل اقتراح مشروع جديد.",
    summary: "اقتراح المشاريع يحتاج عتبة تجمع النضج والتكرار وقابلية القياس.",
    kind: "question",
    stage: "بذرة",
    tags: ["مشاريع", "معيار", "تطبيق"],
    topicId: "topic-product",
    topicTitle: "تصميم المنتجات",
    createdAt: "2026-07-22T08:20:00.000Z",
    updatedAt: "2026-07-25T19:00:00.000Z",
  },
  {
    id: "note-5",
    title: "واجهة هادئة تعني قرارات أوضح",
    content:
      "لا ينبغي أن تعرض الصفحة كل ما يعرفه النظام. الأفضل أن تظهر الإجراء الأقرب والسياق الذي يبرره.",
    summary: "الواجهة الجيدة تخفض كثافة القرار وتكشف السياق عند الحاجة.",
    kind: "idea",
    stage: "تطبيق",
    tags: ["تجربة مستخدم", "تركيز"],
    topicId: "topic-product",
    topicTitle: "تصميم المنتجات",
    createdAt: "2026-07-20T11:45:00.000Z",
    updatedAt: "2026-07-24T09:30:00.000Z",
  },
];

export const demoSources: Source[] = [
  {
    id: "source-1",
    title: "The Extended Mind",
    url: "https://en.wikipedia.org/wiki/The_Extended_Mind",
    author: "Andy Clark & David Chalmers",
    sourceType: "paper",
    status: "complete",
    topicId: "topic-ai-creativity",
    topicTitle: "الذكاء الاصطناعي والإبداع",
    createdAt: "2026-07-22T10:00:00.000Z",
  },
  {
    id: "source-2",
    title: "Make It Stick",
    url: "https://www.hup.harvard.edu/books/9780674729018",
    author: "Brown, Roediger & McDaniel",
    sourceType: "book",
    status: "reading",
    topicId: "topic-learning",
    topicTitle: "علوم التعلّم",
    createdAt: "2026-07-20T08:30:00.000Z",
  },
  {
    id: "source-3",
    title: "Music and Emotion",
    url: "https://en.wikipedia.org/wiki/Music_and_emotion",
    author: "Research collection",
    sourceType: "article",
    status: "unread",
    topicId: "topic-music",
    topicTitle: "الموسيقى وعلم النفس",
    createdAt: "2026-07-18T15:15:00.000Z",
  },
];

export const demoProjects: Project[] = [
  {
    id: "project-1",
    title: "مختبر التعلّم الشخصي",
    description:
      "تجربة أسبوعية تقارن بين الاسترجاع النشط وإعادة القراءة في تعلم اللغة.",
    status: "active",
    progress: 64,
    dueDate: "2026-08-18",
    topicIds: ["topic-learning", "topic-product"],
    taskCount: 8,
    completedTaskCount: 5,
    createdAt: "2026-07-16T09:00:00.000Z",
    updatedAt: "2026-07-28T06:00:00.000Z",
  },
  {
    id: "project-2",
    title: "خريطة الموسيقى والمشاعر",
    description:
      "مجموعة بصرية تربط الخصائص الموسيقية بأنماط الاستجابة العاطفية.",
    status: "idea",
    progress: 22,
    dueDate: null,
    topicIds: ["topic-music", "topic-ai-creativity"],
    taskCount: 5,
    completedTaskCount: 1,
    createdAt: "2026-07-19T14:00:00.000Z",
    updatedAt: "2026-07-25T10:30:00.000Z",
  },
  {
    id: "project-3",
    title: "دليل بناء عقل ثانٍ",
    description:
      "دليل قصير يحول مبادئ تنظيم المعرفة إلى ممارسة يومية قابلة للقياس.",
    status: "active",
    progress: 41,
    dueDate: "2026-09-05",
    topicIds: ["topic-ai-creativity", "topic-learning"],
    taskCount: 10,
    completedTaskCount: 4,
    createdAt: "2026-07-13T12:00:00.000Z",
    updatedAt: "2026-07-27T16:50:00.000Z",
  },
];

export const demoLinks: KnowledgeLink[] = [
  {
    id: "link-1",
    sourceType: "note",
    sourceId: "note-1",
    targetType: "topic",
    targetId: "topic-music",
    relation: "يتقاطع مع",
    confidence: 0.91,
    reason: "كلاهما يدرس أثر جمع الأنماط والتوقعات في إنتاج تجربة جديدة.",
  },
  {
    id: "link-2",
    sourceType: "topic",
    sourceId: "topic-learning",
    targetType: "project",
    targetId: "project-1",
    relation: "يُطبّق في",
    confidence: 0.98,
    reason: "المشروع يحول مبادئ الاسترجاع النشط إلى تجربة قابلة للقياس.",
  },
  {
    id: "link-3",
    sourceType: "note",
    sourceId: "note-5",
    targetType: "project",
    targetId: "project-3",
    relation: "يحسّن",
    confidence: 0.86,
    reason: "مبدأ خفض كثافة القرار يمكن أن يصوغ بنية الدليل.",
  },
];

export const demoMessages: ChatMessage[] = [
  {
    id: "message-welcome",
    role: "assistant",
    content:
      "مرحباً، أنا رفيقك المعرفي. أستطيع البحث في ملاحظاتك، كشف الروابط بينها، وتحويل فكرة مبعثرة إلى خطة مشروع. ما الذي تريد التفكير فيه اليوم؟",
    provider: "demo",
    createdAt: "2026-07-28T08:00:00.000Z",
  },
];
